from typing import Callable, Any

from bier.EndianedBinaryIO import EndianedBytesIO

_TYPE_CONVERTERS: dict[str, Callable[[bytes], Any]] = {
    "bool": lambda x: x[0] == 1,
    "char": lambda x: x[0],
    "byte": lambda x: int.from_bytes(x, "little"),
    # "utf8": lambda x: x,
    # "utf16": lambda x: x,
    # "rsrv0": lambda x: x,
    # "rsrv1": lambda x: x,
    # "rsrv2": lambda x: x,
    # "rsrv3": lambda x: x,
    "uint": lambda x: int.from_bytes(x, "little"),
    "uint8": lambda x: int.from_bytes(x, "little"),
    "uint16": lambda x: int.from_bytes(x, "little"),
    "uint32": lambda x: int.from_bytes(x, "little"),
    "uint64": lambda x: int.from_bytes(x, "little"),
    "uint2": lambda x: list(EndianedBytesIO(x).read_u32_array(2)),
    "uint3": lambda x: list(EndianedBytesIO(x).read_u32_array(3)),
    "uint4": lambda x: list(EndianedBytesIO(x).read_u32_array(4)),
    # "Tag": lambda x: x,
    # "rsrv5": lambda x: x,
    "int": lambda x: int.from_bytes(x, "little", signed=True),
    "int8": lambda x: int.from_bytes(x, "little", signed=True),
    "int16": lambda x: int.from_bytes(x, "little", signed=True),
    "int32": lambda x: int.from_bytes(x, "little", signed=True),
    "int64": lambda x: int.from_bytes(x, "little", signed=True),
    "int2": lambda x: list(EndianedBytesIO(x).read_i32_array(2)),
    "int3": lambda x: list(EndianedBytesIO(x).read_i32_array(3)),
    "int4": lambda x: list(EndianedBytesIO(x).read_i32_array(4)),
    # "rsrv6": lambda x: x,
    # "rsrv7": lambda x: x,
    "float": lambda x: EndianedBytesIO(x).read_f32_le(),
    "float2": lambda x: list(EndianedBytesIO(x).read_f32_array(2)),
    "float3": lambda x: list(EndianedBytesIO(x).read_f32_array(3)),
    "float4": lambda x: list(EndianedBytesIO(x).read_f32_array(4)),
    "float4x4": lambda x: EndianedBytesIO(x).read_f32_array(16),
    # "quaternion": lambda x: x,
    "Transform": lambda x: EndianedBytesIO(x).read_f32_array(10),
    "EulerTransform": lambda x: EndianedBytesIO(x).read_f32_array(9),
    "TiledTransform": lambda x: EndianedBytesIO(x).read_f32_array(11),
    # "rsrv12": lambda x: x,
    # "Color": lambda x: x,
    # "LinearColor": lambda x: x,
    "staticstringA": lambda x: x.decode("utf-8"),
    "IndexedStringA": lambda x: x.decode("utf-8"),
    "staticstringW": lambda x: x.decode("utf-16"),
    "scopestringA": lambda x: x.decode("utf-8"),
    "scopestringW": lambda x: x.decode("utf-16"),
    # "ReflectObject": lambda x: x,
    # "ReflectObjectPtr": lambda x: x,
    # "ReflectObjectVector": lambda x: x,
    # "ReflectObjectPtrVector": lambda x: x,
    # "ResourceReferencePathBase": lambda x: x,
    # "ResourceReferencePath_ITexture": lambda x: x,
    # "EffectDataReferencePath": lambda x: x,
    # "rsrv17": lambda x: x,
    # "rsrv18": lambda x: x,
    # "rsrv19": lambda x: x,
    # "rsrv20": lambda x: x,
    # "rsrv21": lambda x: x,
    # "CharacterKey": lambda x: x,
    # "EmitterVariationID": lambda x: x,
    # "SubEmitterTriggerType": lambda x: x,
    # "SubEmitterProperty": lambda x: x,
    # "EffectXMLVersion": lambda x: x,
    # "EmitterXMLVersion": lambda x: x,
    # "SceneObjectUid": lambda x: x,
    # "CharacterSubKey": lambda x: x,
    # "ContentsCameraKey": lambda x: x,
    # "RegionKey": lambda x: x,
    # "SpawnPositionGroupKey": lambda x: x,
    # "EffectSplineKey": lambda x: x,
    # "TextureIndex": lambda x: x,
    # "InteractionKey": lambda x: x,
    # "KnowledgeKey": lambda x: x,
    # "PortalKey": lambda x: x,
    # "ObjectComponentIndex": lambda x: x,
    # "SceneObjectGuid": lambda x: x,
    # "FormationKey": lambda x: x,
    # "NPCActionKey": lambda x: x,
    # "BitFlag32": lambda x: x,
    # "SplineFloat": lambda x: x,
    # "SplineFloat2": lambda x: x,
    # "SplineFloat3": lambda x: x,
    # "SplineFloat4": lambda x: x,
    # "SplineRef": lambda x: x,
    # "Texture": lambda x: x,
    # "PresetCameraTargetType": lambda x: x,
    # "DetectKey": lambda x: x,
    # "LightPreset": lambda x: x,
    # "BreakableObjectInfoKey": lambda x: x,
    # "Byte4": lambda x: x,
    # "PresetCameraDOFState": lambda x: x,
    # "Short2": lambda x: x,
    # "ColorPreset": lambda x: x,
    # "FieldInfoKey": lambda x: x,
    # "HashCode32": lambda x: x,
    # "TLevel": lambda x: x,
    # "TickCount64": lambda x: x,
    # "SkillKey": lambda x: x,
    # "TypeObstacle": lambda x: x,
    # "ObstacleShapeType": lambda x: x,
    # "SplineTextureGroup": lambda x: x,
    # "CharacterGroupKey": lambda x: x,
    # "TAddOnEventIndex": lambda x: x,
    # "ObstacleUse": lambda x: x,
    # "ComponentReference": lambda x: x,
    # "SendAiEventNextTransform": lambda x: x,
    # "SequencerTarget": lambda x: x,
    # "CommonSequencerTarget": lambda x: x,
    # "SequencerObjectContentsKey": lambda x: x,
    # "TriggerComponentData": lambda x: x,
    # "TGimmickSignalIndex": lambda x: x,
    # "CustomCollisionNodeInfo": lambda x: x,
    # "ReflectObjectReferenceBase": lambda x: x,
    # "ReflectObjectReference": lambda x: x,
    # "AiEventKey": lambda x: x,
    # "CssColor": lambda x: x,
    # "CssUint32": lambda x: x,
    # "CssFloat": lambda x: x,
    # "CssInt": lambda x: x,
    # "TriggerEventHandlerReference": lambda x: x,
    # "SceneObjectUuid": lambda x: x,
    # "ComponentReference2": lambda x: x,
    # "TriggerEventHandlerReferenceSelectable": lambda x: x,
    # "ReflectVectorElementIdType": lambda x: x,
    # "Effect": lambda x: x,
    # "ReflectObjectReferenceBase2": lambda x: x,
}

_TYPE_ALIASES: dict[str, str] = {
    "QuestStateType": "uint",
    "FactionNodeKey": "uint",
    "FactionKey": "uint",
    "FactionNodeStateType": "uint",
    "StageKey": "uint",
    "QuestKey": "uint",
    "RegionKey": "uint",
    "SkillKeyAndLevel": "uint2",
    "GameAdviceInfoKey": "uint",
    "TStackCount": "uint",
    "ItemKey": "uint",
    "RoyalSupplyKey": "uint",
    "FieldInfoKey": "uint",
    "quaternion": "float4",
    "HashCode32": "uint",
    "TPercent": "uint",
    "GlobalGameEventInfoKey": "uint",
    "FactionOperationStateType": "uint",
    "FactionBlockSubType": "uint",
    "StoreKey": "uint",
    "MissionKey": "uint",
    "GimmickInfoKey": "uint",
    "SpawnStyle": "uint",
    "FieldGimmickSaveDataKey": "uint",
    "FieldSaveDataReason": "uint",
    "ItemGroupKey": "uint",
    "LevelGimmickSceneObjectInfoKey": "uint",
    "CharacterKey": "uint",
    "TLevel": "uint",
    "TStat": "uint",
    "SubLevelKey": "uint",
    "TExperience": "uint",
    "TCacheSequenceNo": "uint",
    "ItemNo": "uint",
    "TItemSlotNo": "uint",
    "TEndurance": "uint",
    "TSocketSlotNo": "uint",
    "TickCount64": "uint",
    "Ctc64": "uint",
    "StringInfoKey": "uint",
    "InventoryKey": "uint",
    "ReserveSlotKey": "uint",
    "MercenaryNo": "uint",
    "TEquipSlotNo": "uint",
    "FieldNPCSaveDataKey": "uint",
    "TInventorySlotNo": "uint",
    "FactionSpawnDataKey": "uint",
    "InvestmentPropensity": "uint",
    "MissionUIState": "uint",
    "QuestGaugeKey": "uint",
    "KnowledgeKey": "uint",
    "AlertType": "uint",
    "GimmickTargetType": "uint",
    "TEnchantLevel": "uint",
    "CharacterAppearanceIndexKey": "uint",
    "FactionRelationGroupKey": "uint",
    "NormalizedPathA": "staticstringA",
    "SplineInterpolationType": "uint",
    "BlendType": "uint",
    "SpawningPoolAutoSpawnInfoKey": "uint",
    "ComponentReference2": "uint",
    "VolumeType": "uint",
    "SceneObjectUuid": "uint4",
    "TriggerRegionKey": "uint",
    "LightType": "uint",
    "PbdColliderShapeType": "uint",
    "SkinnedMeshPropertyCollisionShapeType": "uint",
    "ReflectVectorElementIdType": "uint",
    "SplineRotationMode": "uint",
    "ApplySkillCollideType": "uint",
    "LevelActionPointKey": "uint",
    "AreaLightShapeType": "uint",
    "ObstacleUseType": "uint",
    "DecalType": "uint",
    "PascriptKindRaw": "uint",
    "SwitchComponentEventCategory": "uint",
    "TriggerEventHandlerReferenceSelectable": "uint",
    "SequencerSpawnKey": "uint",
    "ShadowType": "uint",
    "TriggerEventConditions": "uint",
    "ReflectObjectReferenceBase2": "uint",
    "Color": "uint",
    "DecalMode": "uint",
    "SceneObjectPriorityLevel": "uint",
}

_MISSING_TYPE_SET: set[str] = set()


def get_converted_value(type: str, value: bytes):
    type = _TYPE_ALIASES.get(type, type)

    conv = _TYPE_CONVERTERS.get(type, None)
    if conv is None:
        if type not in _MISSING_TYPE_SET:
            print("Missing type: ", type)
            _MISSING_TYPE_SET.add(type)

        return value.hex()

    return conv(value)
